/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponentStencil {
        "name": string;
        "options": string;
        "setStates": (newStates: any) => Promise<void>;
        "states": string[] | string;
    }
}
declare global {
    interface HTMLMyComponentStencilElement extends Components.MyComponentStencil, HTMLStencilElement {
    }
    var HTMLMyComponentStencilElement: {
        prototype: HTMLMyComponentStencilElement;
        new (): HTMLMyComponentStencilElement;
    };
    interface HTMLElementTagNameMap {
        "my-component-stencil": HTMLMyComponentStencilElement;
    }
}
declare namespace LocalJSX {
    interface MyComponentStencil {
        "name"?: string;
        "options"?: string;
        "states"?: string[] | string;
    }
    interface IntrinsicElements {
        "my-component-stencil": MyComponentStencil;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component-stencil": LocalJSX.MyComponentStencil & JSXBase.HTMLAttributes<HTMLMyComponentStencilElement>;
        }
    }
}
